### ISSUE TITLE
adding +x to postBuild on Windows

### ISSUE THREAD

**Issue by annefou** [annefou/jupyter_dashboards#9]
From my windows laptop, I did:
git update-index --chmod=+x postBuild

then git add & commit & push but postBuild does not have exectuable permissions.

When I try from Linux:
chmod +x postBuild 

git add & commit & push
then it works perfectly. 

Is there anything else to do on windows apart from:
git update-index --chmod=+x postBuild

**Comment by minrk** [comment]
postBuild is executable on Linux. I don't think Windows has the execute bit. When I check on Binder, I can see that the postBuild script has run, so I think it's all set there.

There is one thing in the postBuild script that won't have an effect, though: the `export PATH=...` will run in the script, but has no effect outside the script itself.

I would say the simplest solution would be to install things in the default prefix, rather than edit PATH and LD_LIBRARY_PATH. I'll look at updating postBuild to do that.

**Comment by annefou** [comment]
Yes I noticed export PATH has no effect... I managed to run SNOWPACK within a jupyter dashboard by specifying the full path but I agree it's better to use the default path...

**Comment by minrk** [comment]
postBuild PATH stuff is fixed in #12 and it is executable, so I think we're set with this one
